export default  {
    path:'/careerManagement',
    name:'生涯管理',
    redirect:'/careerManagement/main',
    component:()=>import('../views/careerManagement/index'),
    children:[
        {
            path:'/careerManagement/main',
            name:'生涯管理主页',
            component:()=>import('../views/careerManagement/main'),
        },
        {
            path:'/careerManagement/careerAnchor',
            name:'职业定位',
            component:()=>import('../views/careerManagement/careerAnchor'),
        },
        {
            path:'/careerManagement/major',
            name:'专业定位',
            component:()=>import('../views/careerManagement/major'),
        },
        {
            path:'/careerManagement/university',
            name:'院校定位',
            component:()=>import('../views/careerManagement/university'),
        },
        {
            path:'/careerManagement/goal',
            name:'我的目标',
            component:()=>import('../views/careerManagement/goal')
        },
        {
            path:'/careerManagement/decompose',
            name:'目标分解',
            component:()=>import('../views/careerManagement/decompose')
        },
        {
            path:'/careerManagement/plan',
            name:'行动计划',
            component:()=>import('../views/careerManagement/plan')
        },
        {
            path:'/careerManagement/matchingSchools',
            name:'成绩匹配院校',
            component:()=>import('../views/careerManagement/matchingSchools')
        },
        {
            path:'/careerManagement/academicPlanningReport',
            name:'学业规划报告',
            component:()=>import('../views/careerManagement/academicPlanningReport')
        }
    ]
}
